config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #routes lists (index, new, show, create)
  resources :lists, only: [:create, :index, :show, :new] do

    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  #route : /lists/:list_id/bookmarks/:id(.:format) 
  #create/new/destroy

  #new
  def new
    @bookmark = Bookmark.find(params[:list_id])
    @bookmark = Bookmark.new
  end
  
  
  #bookmarks#destroy
  #def destroy
  #  @bookmark = Bookmark.find(params[:list_id])
  #  @bookmark.destroy
  #  redirect_to lists_path
  #end
  def create
    @list = List.find(params[:list_id])
    @bookmark = bookmark.find(params[:bookmark_id][:bookmark])
    @bookmarks.each do
      @bookmark = Bookmark.new
      @bookmark.list = list
      @bookmark.save
    end
    redirect_to list_bookmarks_path(@list.bookmark)
  end

  def destroy
    @bookmark = Bookmark.find(params[:list_id])
    @bookmark.destroy
    redirect_to list_bookmarks_path(@list.bookmark), notice: 'Bookmark was successfully destroyed.'
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new(list_params)
    @list.save
  end
  
  def index
    @list = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created.'
    else
      render :new 
  end

  def show
    @show = Show.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/bookmark.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h1>Add new bookmark for <%= @list.name %></h1>

      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :bookmark, collection: Bookmark.all, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
        <%= f.submit "Add Bookmark", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/create.html.erb
<h1>Creating List</h1>

<%= render 'form', list: @list %>
<%= link_to 'Show', @list %> 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @list.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', List %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>